name: social-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typing-extensions=4.5.0  # Add this specific version
  - pip:
    - python-dotenv==1.0.0
    - supabase==2.0.3
    - elevenlabs==1.0.0  # Using an older, more stable version
    - fal-serverless==0.6.41
    - fal
    - pillow==10.0.0
    - pytest==7.4.0
    - requests==2.31.0