// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpkwrnywumaosryedqwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwa3dybnl3dW1hb3NyeWVkcXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTI2MTcsImV4cCI6MjA1NTgyODYxN30.mTIdAnAW4ZriSdUezRbh6CG8tXyEkLEvPBSx8et926Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);