name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Python Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          # Install any additional test/coverage tools you need.
          pip install pytest pytest-asyncio httpx pytest-cov
          
      - name: Run Backend Tests with Coverage
        run: |
          cd backend
          # Automatically discover and run all tests in the tests/ directory.
          # The --cov and --cov-fail-under options help you track/enforce coverage.
          python -m pytest tests --cov=src --cov-report=term-missing --cov-fail-under=80
        env:
          FAL_KEY: ${{ secrets.FAL_KEY }}