name: Build & Push Docker to GCR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # for workload identity (optional)

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for gcr.io
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/fluffyduck:latest .

      - name: Push image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/fluffyduck:latest 